# ----------------------------------------------------------------------
# © 2025 KR-Labs. All rights reserved.
# KR-Labs™ is a trademark of Quipu Research Labs, LLC,
# a subsidiary of Sudiata Giddasira, Inc.
# ----------------------------------------------------------------------
# SPDX-License-Identifier: MIT

name: Security & IP Protection

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main]

jobs:
  copyright-verification:
    name: Copyright Header Verification
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.11'
      
      - name: Verify copyright headers
        run: |
          python scripts/security/verify_copyright_headers.py --repo .
          
      - name: Check trademark notices
        run: |
          python scripts/security/check_trademarks.py --repo .
  
  secret-scanning:
    name: Secret Detection
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Full history for gitleaks
      
      - name: Run gitleaks
        uses: gitleaks/gitleaks-action@v2
        with:
          config-path: .gitleaks.toml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        continue-on-error: true
  
  license-compliance:
    name: License Compliance Scan
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    steps:
      - uses: actions/checkout@v4
      
      - name: Check LICENSE file exists
        run: |
          if [ ! -f LICENSE ]; then
            echo "❌ No LICENSE file detected!"
            exit 1
          fi
          echo "✅ LICENSE file found"
      
      - name: Check for GPL licenses in dependencies
        run: |
          pip install pip-licenses
          pip install -e .
          pip-licenses --format=json > licenses.json
          cat licenses.json
          
          # Check for GPL (not allowed in our Apache 2.0 project)
          if pip-licenses | grep -qi "gpl"; then
            echo "⚠️ GPL license detected in dependencies - review required"
            exit 1
          fi
          
          echo "✅ License compliance check passed"
        continue-on-error: true
      
      - name: Upload license report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: license-report
          path: licenses.json
        continue-on-error: true
  
  dependency-review:
    name: Dependency Security Review
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    steps:
      - uses: actions/checkout@v4
      
      - name: Dependency Review
        uses: actions/dependency-review-action@v4
        with:
          fail-on-severity: moderate
        continue-on-error: true
